[package]
name = "nvim-oxi-template-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10", "neovim-nightly", "test", "libuv"] }
